### ISSUE TITLE
Composer.lock file in module

### ISSUE THREAD

**Issue by leonhelmus** [flowmailer/m2connector#15]
Can the **composer.lock** file be removed from the module. A composer.lock should only be available in a project not a module in my opinion.

**Comment by reyostallenberg** [comment]
What are the problems you are encountering from this?

**Comment by leonhelmus** [comment]
It could intefere with the packages installed in the project.

When looking in this threat it explains why you shoudn't add it for packages and libraties but should add it in the project:
https://laracasts.com/discuss/channels/laravel/why-composerlock-is-not-in-the-gitignore

I did have the issue in composer that this prevented me from updating a package.

But its one of the practices we use for our company.

**Comment by reyostallenberg** [comment]
As far is I know, composer uses only the lock file of the root project for reading on `install` and writing on `update`.
So you shouldn't have any issues with it. If you have, please send me the exact example(s) so I can verify the issue.
