### ISSUE TITLE
ObjectManager not used for FlowmailerAPI

### ISSUE THREAD

**Issue by pmzandbergen** [flowmailer/m2connector#5]
Please use the ObjectManager to allow plugins to hook in. For example in the TransportPlugin, instead of:

```
public function aroundSendMessage(TransportInterface $subject, \Closure $proceed)
{
    ...
    $api = new FlowmailerAPI($accountId, $apiId, $apiSecret);
```

Use a factory:

```
public function __construct(FlowmailerAPIFactory $flowmailerApiFactory, ...) {
    $this->flowmailerApiFactory = $flowmailerApiFactory;
    ...
}
...
public function aroundSendMessage(TransportInterface $subject, \Closure $proceed)
{
    ...
    $api = $this->flowmailerApiFactory->create($accountId, $apiId, $apiSecret);
```

This allows modifications and bug fixes on the FlowmailerAPI class without duplicating code.

**Comment by flowmailer-richard** [comment]
This was changed by the commit above. If you actually use this facility in a way that could be relevant to further development of the connector, please let us know.
