### ISSUE TITLE
Call to protected method from \Flowmailer\M2Connector\Registry\MessageData

### ISSUE THREAD

**Issue by pmzandbergen** [flowmailer/m2connector#6]
**Error**
Fatal error: Uncaught Error: Call to protected method Flowmailer\M2Connector\Registry\MessageData::reset() from context 'Flowmailer\M2Connector\Plugin\TransportBuilderPlugin'

**Cause**
```
	public function beforeReset(TransportBuilder $transportBuilder)
	{
		$this->_messageData->reset();
		return null;
	}
```

You can not call a protected method. Please note that the class in question (```Flowmailer\M2Connector\Registry\MessageData```) is part of this library.

**Fix**
Use a public method instead of protected.

**Comment by flowmailer-richard** [comment]
Fixed.
